### ISSUE TITLE
Código terminado

### ISSUE THREAD

**Issue by sandra86code** [sandra86code/ProyectoJuegoJaca#2]
Inma, ya tengo terminado el código, le he pasado las pruebas unitarias y todas pasan. Por si le puedes echar un vistazo a ver si todo está bien.

**Comment by sandra86code** [comment]
He realizado unas modificaciones en setX() y setY() de la clase Constante, ya que no era correcta.

Proyecto entregado

**Comment by ioliasa** [comment]
oK
